# Generated by Django 5.0.4 on 2025-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальное название')),
                ('title', models.CharField(max_length=200, verbose_name='Навзвание товара')),
                ('image', models.CharField(max_length=50, verbose_name='Фото товара')),
                ('desc', models.TextField(verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Імʼя')),
                ('surname', models.CharField(max_length=200, verbose_name='Прізвище')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('delivery_method', models.CharField(choices=[('courier', 'Кур’єрська доставка'), ('pickup', 'Самовивіз'), ('post', 'Пошта')], default='courier', max_length=20, verbose_name='Спосіб доставки')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('basket', models.JSONField(default=list, verbose_name='Кошик')),
            ],
        ),
    ]
