# Generated by Django 5.0.4 on 2025-05-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
