# Generated by Django 5.0.4 on 2025-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_image_alter_item_price_alter_item_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Уникальна назва'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items/', verbose_name='Додаткове фото'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основне зображення'),
        ),
    ]
